theme: jekyll-theme-minimal
title: Luke M Shepherd's Website
description: A slightly (very) beliguered UCL student mainly working on medical imagery and neural networks.

github_username: lukemshepherd

minima:
  social_links:
    twitter: lmortshepherd
    github: lukemshepherd
