theme: jekyll-theme-minimal
title: Luke M Shepherd's Website
description: Some descritpion

github_username: lukemshepherd
twitter_username: lmortshepherd

minima:
  social_links:
    twitter: lmortshepherd
    github: lukemshepherd
