theme: jekyll-theme-minimal
title: Luke M Shepherd's Website
description: A slightly (very) beliguered UCL student mainly working on medical imagery and neural networks.

Technical CCR cave diver with a soft spot for scientific diving and photogrammetry.

I own way too many sets of dice and am the kind of person who grinds and weighs their own coffee, because it tastes better and volumetric measurements are for provincial towns on the frontiers of civilisation not a kitchen.

github_username: lukemshepherd
twitter_username: lmortshepherd

minima:
  social_links:
    twitter: lmortshepherd
    github: lukemshepherd
